apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsyslog-pv-claim
  namespace: monitoring
spec:
  storageClassName: default-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog
  namespace: monitoring
  labels:
    app: rsyslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: ninjatec/rsyslog:1.0.5 # {"$imagepolicy": "flux-system:rsyslog"}
        ports:
        - name: udp
          containerPort: 514
          protocol: UDP
        - name: tcp
          containerPort: 514
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
        volumeMounts:
        - name: rsyslog-pv-claim
          mountPath: "/var/log"
      - name: grafana-agent
        image: grafana/agent:latest
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
        volumeMounts:
        - name: rsyslog-pv-claim
          mountPath: "/var/log"
        - name: config-volume
          mountPath: "/etc/agent/agent.yaml"
          subPath: agent.yaml
      nodeSelector:
        kubernetes.io/hostname: k8snode1
      restartPolicy: Always
      volumes:
      - name: rsyslog-pv-claim
        persistentVolumeClaim:
          claimName: rsyslog-pv-claim
      - name: config-volume
        configMap:
          name: grafana-agent-logs
