apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rsyslog
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: ssh://git@github.com/ninjatec/syslogtoloki