apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: rsyslog
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: rsyslog
  path: ./
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg